-- AlterTable
ALTER TABLE "SensorReadings" ALTER COLUMN "xAxis" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "yAxis" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "zAxis" SET DATA TYPE DOUBLE PRECISION;
